config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'

  resources :users, only: :show
  resources :orders, only: [:index, :show], param: :number do
    patch :cancel, on: :member
  end

  resources :reports, only: :index do
    get :coupons, on: :collection
    get :sales, on: :collection
  end
end

app/models/order.rb
class Order < ApplicationRecord
  self.per_page = 10

  BUILDING = "building"
  ARRIVED = "arrived"
  CANCELED = "canceled"
  STATES = [BUILDING, ARRIVED, CANCELED].freeze

  validates_presence_of :user_id, :state

  validates   :total,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :user
  belongs_to :address

  has_many :order_items
  has_many :payments

  delegate :name, to: :user, prefix: true
  delegate :email, to: :user, prefix: true

  # loop over STATES constant to create corresponding scopes and a couple of
  # convenience methods
  STATES.each do |the_state|
    scope "#{the_state}", -> { where(state: the_state) }
    define_method("#{the_state}?".to_sym) { the_state == state }
    define_method("#{the_state}!".to_sym) { update(state: the_state) }
  end

  def to_param
    number
  end

  def self.search(query)
    query.strip!

    results = where(number: query).or(where(id: query))
    return results unless results.blank?

    results = joins(:user).where(users: { email: query })
    return results unless results.blank?

    results = joins(:user).where(users: { name: query })
    return results unless results.blank?

    like_query = 'users.email like ? or users.name like ?'
    results = joins(:user).where(like_query, "%#{query}%", "%#{query}%")

    results
  end

  def color_class
    return 'info' if building?
    return 'danger' if canceled?
    return 'success' if arrived?
    'primary'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order!, only: [:show, :cancel]

  def index
    @orders = Order.all.paginate page: params[:page]
    filter_orders
  end

  def show
  end

  def cancel
    @order.canceled!
    @order.order_items.update_all(state: OrderItem::RETURNED)
    @order.payments.update_all(state: Payment::REFUNDED, refunded_at: Time.now)

    redirect_to @order, flash: { notice: 'Order was successfully canceled' }
  end

  private

  def filter_orders
    if (params.has_key?(:q) && params[:q].present?)
      @orders = @orders.search params[:q]
    end

    if (params.has_key?(:user_id) && params[:user_id].present?)
      @orders = @orders.where(user_id: params[:user_id])
    end

    if (params.has_key?(:state) && params[:state].present?)
      @orders = @orders.where(state: params[:state])
    end
  end

  def find_order!
    @order = Order.find_by!(number: params[:number])
  end
end

app/views/orders/_order_items.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %strong Order Items
      .panel-body
        %table.table.table-striped.table-hover
          %tr
            %th ID
            %th Quantity
            %th Price
            %th State
            %th Type
          - order_items.each do |item|
            %tr
              %td= item.id
              %td= item.quantity
              %td= number_to_currency item.price.to_f
              %td= item.state
              %td= item.source_type

app/views/orders/_payments.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %strong Payments
      .panel-body
        %table.table.table-striped.table-hover
          %tr
            %th ID
            %th Amount
            %th State
            %th Refunded At
            %th Payment Type
            %th Completed At
          - payments.each do |payment|
            %tr
              %td= payment.id
              %td= number_to_currency(payment.amount.to_f)
              %td= payment.state
              %td= payment.refunded_at.present? ? payment.refunded_at : '-'
              %td= payment.payment_type
              %td= payment.completed_at

app/views/orders/index.haml
- if @orders.blank?
  %h1 No orders found!

- else
  %h1 Orders
  .row
    .col-md-12
      = form_with(url: orders_path, method: :get, local: true) do
        = text_field_tag :q, params[:q], placeholder: 'search'
        = submit_tag 'search'
  %table.table.table-hover
    %tr
      %th Order Number
      %th Name
      %th Email
      %th State
      %th Created At

    - @orders.each do |order|
      %tr
        %td= link_to order.number, order
        %td= link_to order.user_name, orders_path(user_id: order.user&.id)
        %td= order.user_email
        %td
          = link_to order.state, orders_path(state: order.state),
          class: "badge progress-bar-#{order.color_class}"
        %td= order.created_at

= will_paginate @orders

app/views/orders/show.haml
.row
  .col-md-9
    %h1
      Order:
      = @order.number
      %span{class: "badge progress-bar-#{@order.color_class}"}
        = @order.state
  .col-md-3
    - unless @order.canceled?
      = link_to 'Cancel Order', cancel_order_path(@order), class: 'btn btn-danger',
        data: { confirm: 'Are you sure you want to cancel this order?' },
        method: :patch

.row
  .col-md-6
    %h3 User Info
    %p
      %br/
      = link_to @order.user_name, @order.user
      %br/
      = @order.user_email

  .col-md-6
    %h3 Address
    %p
      %br/
      = @order.address.address1
      - if @order.address.address2.present?
        %br/
        = @order.address.address2
      %br/
      = @order.address.city_state_zip

= render partial: 'order_items', locals: { order_items: @order.order_items }
= render partial: 'payments', locals: { payments: @order.payments }