config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'

  resources :users, only: :show
  resources :orders, only: [:index, :show], param: :number do
    patch :cancel, on: :member
  end

  resources :reports, only: :index do
    get :coupons, on: :collection
    get :sales, on: :collection
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Dwight Scott -- Wantable Code Challenge

    = csrf_meta_tags
    = csp_meta_tag
    = tag "meta", "http-equiv" => "Accept-CH", content: "DPR, Viewport-Width, Width"
    = tag 'meta', {"http-equiv" => "Accept-CH", content: "width=device-width, initial-scale=1.0, user-scalable=no", name: "viewport", id: "vp"}, true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          =link_to root_path, class: "navbar-brand" do
            =image_tag "logo"

        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: active_class('orders')}
              =link_to orders_path do
                Orders

            %li{class: "dropdown #{active_class('reports')}"}
              = link_to '#', class: "#{active_class('reports')} dropdown-toggle",
                data: { toggle: :dropdown } do
                Reports
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'Sales', sales_reports_path
                %li= link_to 'Coupons', coupons_reports_path

    .container-fluid{role: "main"}
      .row
        .col-md-12
          - if flash[:notice]
            .alert.alert-info
              %strong Notice:
              = flash[:notice]
          = yield